/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Rescuable } from "../Rescuable";

export class Rescuable__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Rescuable {
    return new Contract(address, _abi, signerOrProvider) as Rescuable;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
    ],
    name: "rescue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
